### ISSUE TITLE
Working with retries and retryTimeout

### ISSUE THREAD

**Issue by AliaksandrKot** [camunda/camunda-external-task-client-js#11]
Right now I didn't find how to work with ``retries`` and setting up ``retryTimeout``.
In the previous version of the application, I added this support manually but I think it would be the good feature out of the box. Or maybe I missed something?

Thanks in advance.

**Comment by tasso94** [comment]
Hey @AliaksandrKot,

could you please elaborate a bit on what you mean exactly?

Cheers,
Tassilo
