### ISSUE TITLE
Synchronous task processing

### ISSUE THREAD

**Issue by agualbbus** [camunda/camunda-external-task-client-js#15]
It seems that tasks are being processed synchronously:

[Client.js#L168](https://github.com/camunda/camunda-external-task-client-js/blob/master/lib/Client.js#L168):

``` javascript
tasks.forEach(executeTask); // forEach is sync.
```

[Client.js#220](https://github.com/camunda/camunda-external-task-client-js/blob/master/lib/Client.js#L220)
``` javascript
  executeTask(task) {
    const taskService = this.taskService;
    const topicSubscription = this.topicSubscriptions[task.topicName];
    const variables = new Variables(task.variables, {
      readOnly: true,
      processInstanceId: task.processInstanceId,
      engineService: this.engineService
    });
    const newTask = { ...task, variables };
    try {
      topicSubscription.handler({ task: newTask, taskService });
      this.emit("handler:success", task);  // this means we are waiting for topicSubscription.handler
    } catch (e) {
      this.emit("handler:error", e);
    }
  }
```
I´ve noticed this because while stress testing our Camunda implementation with the following settings:

24 workers consuming Camunda rest-api with the following settings.

* maxTasks: 300
* asyncResponseTimeout: 20000
* lockDuration: 20000
* interval: 50

The process has 2 dummy external tasks.

Instances created throughput: 300/s.
Instances finished  throughput: 105/s .

The more I increment the amount of simultaneous tasks fetched per worker the more the latency increases. That leaves me to decrease the `maxTasks` and `lockDuration` parameters, but increases the amount of requests to the API. 

Maybe something like this could help: [async-each](https://github.com/paulmillr/async-each)

**Comment by ingorichtsmeier** [comment]
I've checked the situation in the java external task client which is the same there. Inspecting the access log i found that each fetch-and-lock call just takes 40-60 ms if you call for maxtasks = 1. So you don't need to worry about the load of many requests from the client, especially with long running computations (> 2 secs)

I think that you can better scale the client with the help of hardware and the operating system than with threads in java scripts. Long polling combined with maxtasks = 1 decreases the number of calls, when there is nothing to do. And starting more clients, maybe dozens of them, will use the power of the OS to keep track of the hardware and minimizes the possible concurrency issues, that a programmer can trap into.

**Comment by agualbbus** [comment]
@ingorichtsmeier thanks for your reply. I´ve already forked this library to adapt it to our needs, please take a look to my proposal. We've successfully  reduced latency.
