### ISSUE TITLE
handleBpmnError method takes variables as a param but doesnt set these on the process

### ISSUE THREAD

**Issue by Lau-Ren** [camunda/camunda-external-task-client-js#17]
camunda-external-task-client-js method takes a variables param. 
ie - snippet it from camunda-external-task-client-js source code
```
  /**
   * @throws HTTPError
   * @param id
   * @param errorCode
   * @param errorMessage
   * @param variables
   * @returns {Promise}
   */
  handleBpmnError({ id }, errorCode, errorMessage, variables) {
    return this.post(`/external-task/${id}/bpmnError`, {
      json: true,
      body: { errorCode, workerId: this.workerId, errorMessage, variables }
    });
  }
```

These are added to the body of the post request to the camunda rest API, but if you look at the [docs](https://docs.camunda.org/manual/7.9/reference/rest/external-task/post-bpmn-error/) this camunda end point doesn't actually support variables in the body of this request.

This is an issues because it gives the impression that variables passedthrough will be set on the process, but this isnt the case

**Comment by tasso94** [comment]
Hey Lauren,

thanks for reaching out to us with your question.

Setting variables on `handleBpmnError` is a new feature of Camunda BPM 7.10 which has been released together with the NodeJS External Task Client 1.1.1 recently. 

Please see the updated documentation for [`POST /external-task/{id}/bpmnError`](https://docs.camunda.org/manual/7.10/reference/rest/external-task/post-bpmn-error/) as well as the [compatibility matrix](https://docs.camunda.org/manual/7.10/user-guide/ext-client/compatibility-matrix/) for the External Task Client.

Cheers,
Tassilo
