### ISSUE TITLE
Invalid date when we set a date and use get method through Variables class

### ISSUE THREAD

**Issue by OlivierAlbertini** [camunda/camunda-external-task-client-js#18]
Hi,

How to reproduce : 
```js
      const vars = new Variables();
      vars.set('date', new Date());
      const date = vars.get('date'); // invalid date
```

### REPL
https://runkit.com/olivieralbertini/camunda-external-task-client

Possible solution :
https://github.com/camunda/camunda-external-task-client-js/blob/master/lib/__internal/utils.js#L151
Change for :
`value = value.toISOString().replace(/Z$/, "+00:00");`

I can make a PR if you want to.
Let me know. Thanks

**Comment by marstamm** [comment]
Hey @OlivierAlbertini ,

Thank you for you patience. I was able to reproduce this bug an created the ticket [CAM-11130](https://jira.camunda.com/browse/CAM-11130) and #64 for it.
We plan to have it fixed with the next release of the external task client.

Cheers
