### ISSUE TITLE
Add TypeScript type definitions

### ISSUE THREAD

**Issue by drochgenius** [camunda/camunda-external-task-client-js#20]
TypeScript type definitions don't seem to be available, neither in the codebase, nor as a `@type/camunda-external-task-client` package.

I'm happy to contribute type definitions. Please let me know if I can open a PR for that.

Regards

**Comment by subhendu-de** [comment]
This is really needed and I am looking for typescript definitions also.

**Comment by tasso94** [comment]
Hi Dominique,

support for TypeScript is right now not in the scope of the product.

However, you could create a separate repository which provides the type definitions. It could than be handled as a community extension [1].

Cheers,
Tassilo

[1] https://docs.camunda.org/manual/7.11/introduction/extensions/

**Comment by drochgenius** [comment]
Hi @tasso94 ,

I understand why you don't want to add TypeScript definitions in this repo, since it's yet another thing to maintain.

Thanks for explaining the preferred approach, I will read about community extensions and follow this route.

Regards

**Comment by MacRusher** [comment]
For everyone interested in TypeScript definitions for camunda-external-task-client-js, a DefinitelyTyped package is already published.

You can install types with `npm install @types/camunda-external-task-client-js`.

**Comment by drochgenius** [comment]
Awesome, thanks @MacRusher
