### ISSUE TITLE
Use priority is not working

### ISSUE THREAD

**Issue by bhatnaa007** [camunda/camunda-external-task-client-js#47]
I have written my client to listen for particular topic say "test".
I have written two taks one with priority 100 and another with priority 200 for same topic.
I have configure the client with property "usePriority: true".
It always takes the task which I triggered first irrespective of priority.

Could you please help me how to implement the same or I am missing something

**Comment by marstamm** [comment]
Hi @bhatnaa007 ,

Sorry for the late reply, we do not check the issues that often. With the release of 1.3.0, it is now possible to Fetch using Priority. Let me know if the problem persists.
