### ISSUE TITLE
Failed to compile.

### ISSUE THREAD

**Issue by lafeber** [camunda/camunda-external-task-client-js#5]
`./node_modules/camunda-external-task-client-js/lib/BasicAuthInterceptor.js`

Module parse failed: Unexpected token (27:13)
You may need an appropriate loader to handle this file type.
   
      interceptor(config) {
        return { ...config, (headers: { ...config.headers, ...this.header }) };
      }
    }

I'm looking into the issue but I'm relatively new to node.

**Comment by siffogh** [comment]
Hi @lafeber, what node version are you using? Are you using a node version >= 8.9.4 like specified in the docs?

**Comment by lafeber** [comment]
Yes, I'm using version v9.8.0. It doesn't seem to have the syntax-object-rest-spread ?

**Comment by siffogh** [comment]
I just noticed a syntax error in the code you provided, there is indeed an unexpected character `(`.

I would replace the snippet with:

```js
interceptor(config) {
    return { ...config, headers: { ...config.headers, ...this.header } };
  }
```
(Just like the in [BasicAuthInterceptor](https://github.com/camunda/camunda-external-task-client-js/blob/master/lib/BasicAuthInterceptor.js) )

**Comment by lafeber** [comment]
Sorry, I didn't paste the original snipped, just something I tried. The original code still gives the error.

However, it works when running as a standalone node app - instead of inside my react app, so I'll close this issue.
