### ISSUE TITLE
Logging to verbose

### ISSUE THREAD

**Issue by pixie79** [camunda/camunda-external-task-client-js#55]
Hi,

Can we implement a logger like winston? Currently logging is to console and very verbose. So especially on polling we get very full logs quickly. It would be better if the following logs :
executor         | ✓ polled 0 tasks
executor         | polling
executor         | ✓ polled 0 tasks
executor         | polling
executor         | ✓ polled 0 tasks
executor         | polling
executor         | ✓ polled 0 tasks

could be set to "Silly level" but then if a task is found that is at info.

Thanks

Mark

**Comment by pvoisin** [comment]
Definitely, the library needs to rely on a logging library.

**Comment by marstamm** [comment]
Hey all,

First of: thanks for your patience and sorry for the late reply.

I agree that a configurable log level is required if you want to use this in production. For that, I created a ticket [here](https://jira.camunda.com/browse/CAM-11129) as well as #63. You can follow the progress there.

As you can see, we are not using winston, but you can easily create your own logger using the `use` interface described [here](https://github.com/camunda/camunda-external-task-client-js/blob/master/docs/Client.md#new-clientoptions). We are always happy about pull requests from the community.
