### ISSUE TITLE
Make logger an actual middleware

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-external-task-client-js#8]
I'm struggling a little bit to understand the `middleware` concept used to extend the external task client.

I presume a middleware is a simple function that receives the client as the argument.

If that is the case, why is the `logger` not a middleware such as:

```javascript
function Logger(client) {
  client.on('foo', function(...) {
    console.log('bar');
  });
}

module.exports = Logger;
```

(Note that the use of `class` inside middleware does not help too much, as classes cannot be middlewares; they cannot be called with the client argument but must be instantiated via `new`).

From the API perspective it would then be possible to expose all middlewares in the same way.

```javascript
new Client({
  ...,
  use: [
    Logger,
    Foo,
    Bar,
    BasicAuthInterceptor
  ]
});
```

**Comment by siffogh** [comment]
@nikku this is solved by https://github.com/camunda/camunda-external-task-client-js/commit/fe16911e49869d2ec85fbbb0f2c0881619c25f82
