### ISSUE TITLE
Bearer Token Interceptor

### ISSUE THREAD

**Issue by aminmc** [camunda/camunda-external-task-client-js#9]
Hi,

Is it possible to create a bearer token interceptor instead of a basic auth? I'm thinking of implementing a version that makes a request to keycloak and then gets a token which I would then like to pass onto Camunda REST API. Just wanted to check if this was feasible as the request to get a token would be a promise.

Thanks

**Comment by siffogh** [comment]
Hi @aminmc, you can create [an interceptor function](https://github.com/camunda/camunda-external-task-client-js/blob/master/docs/Client.md#about-interceptors) to do so.

It doesn't really matter if the request is a asynchronous. You can make the request, get the token and then initialise your Client. The interceptor can use that token you got from the request (could be passed to it through some config option) and add it to the header of every request.

**Comment by aminmc** [comment]
hi @siffogh , thanks for your reply. That makes sense I guess the issue is refreshing the token which would require me to re-create the client with the new token.  Not sure if that would be an issue?

**Comment by siffogh** [comment]
You can have logic for refreshing the token in the interceptor itself. If you wish, you could perhaps create a pull request to add an example about bearer authentication or share some code snippet. I would be happy to assist you in both cases.

**Comment by aminmc** [comment]
@siffogh Sounds good to me. I'll knock up an example.

**Comment by aminmc** [comment]
Hi @siffogh,

So something in the lines of:
```
requestToken(config).then((token) => {
    const clientConfig = {
        baseUrl: '<external-task-url>',
        use: logger,
        interceptors: new BearerTokenInterceptor(token),
        workerId: 'worker-id'
    };
    client = new Client(clientConfig);
   //register handlers
}).catch((error) => {
    logger.error("Failed to get access token!");
});
```

The BearerToken interceptor is similar to the BasicAuthInterceptor in that it takes the token and creates an Authorization token.

I'm not quite sure how the refresh check can happen in the interceptor...as the refresh check is a promise.  The only way I can think this might work is do some form of setInterval (...) and have the function stop the client and re-create it with a new token.  The interval is based around the access token expiry. 

Thanks again for your help and assistance with this.

**Comment by aminmc** [comment]
Also I'm noticing a strange behaviour by adding the token interceptor. The following code catches the exception...

```
 try {
      const { body } = await got(url, newOptions);
      return body;
    } catch (e) {
      throw e.response ? e.response.body.message : e;
    }
```

When I inspect 'e' the method is a GET instead of a POST which causes a 405 response to be returned.

My interceptor:

```
constructor(options) {
        if (!options || !options.token) {
            throw new Error("No bearer token defined")
        }

        this.getHeader = this.getHeader.bind(this);
        this.interceptor = this.interceptor.bind(this);
        this.header = this.getHeader(options.token);
        return this.interceptor;
    }

    getHeader(token) {
        return {
            Authorization: `Bearer ${token}`
        }
    }

    interceptor(config) {
        return {config, headers: {...config.headers, ...this.header}};
    }
```

I've followed the basic principles of the Basic interceptor...no idea where the GET is coming from :)

**Comment by siffogh** [comment]
Hi @aminmc, I apologise for the late response. It depends if failed requests with expired tokens matter to you or not. If it doesn't matter that some requests fail, then you don't need to stop the client. The BearerTokenInterceptor can have the setInterval logic. Could be something like this:

```js
class BearerTokenInterceptor {
  constructor() {
    this.requestToken = this.requestToken.bind(this);
    this.interceptorFunction = this.interceptorFunction.bind(this);

    // in this case, INTERVAL should be the interval of expiry
    const INTERVAL = 3000;
    this.requestToken();
    setInterval(this.requestToken, INTERVAL);
    return this.interceptorFunction;
  }

  async requestToken() {
    // get token from some api
    this.token = await someRequest();
  }

  interceptorFunction(config) {
    // adds this.token to the config
    console.log("interceptor: ", this.token);
  }
}
```

**Comment by aminmc** [comment]
Hey @siffogh, 
Thanks for your reply.  The initial token will be undefined but subsequent headers has the correct token which works.  

Cheers for your help!

**Comment by yoldar** [comment]
Here is complete example:

        const request = require('request-promise-native');
        const util = require('util');
        const MISSING_AUTH_PARAMS =
            "Couldn't instantiate BearerTokenInterceptor, missing configuration parameters"

        class BearerTokenInterceptor {
          /**
           * @throws Error
           */
          constructor(options) {
            if (!options || !options.clientId || !options.clientSecret || !options.baseUrl || !options.readlmId || !options.interval) {
              throw new Error(MISSING_AUTH_PARAMS);
            }
            /**
             * Bind member methods
             */
            this.requestToken = this.requestToken.bind(this);
            this.interceptor = this.interceptor.bind(this);
            this.options = options;

            this.requestToken();
            setInterval(this.requestToken, options.interval);
            return this.interceptor;
          }

          async requestToken() {
            const response = await request({
              url: `${this.options.baseUrl}/auth/realms/${this.options.readlmId}/protocol/openid-connect/token`,
              method: 'POST',
              auth: {
                user: this.options.clientId,
                pass: this.options.clientSecret
              },
              form: {
                'grant_type': 'client_credentials',
              }
            });
            const json = JSON.parse(response);
            console.log(`Access token updated: ${json.access_token}`);
            this.header = { Authorization: `Bearer ${json.access_token}` };
          }   

          interceptor(config) {
            return { ...config, headers: { ...config.headers, ...this.header } };
          }
        }

        module.exports = BearerTokenInterceptor;
